apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: route-reader
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quay-s3-setup-route-reader
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: route-reader
subjects:
- kind: ServiceAccount
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}

