apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-users
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "9"  # Layer 1: Create before user creation job
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.global.secretStore.name }}
    kind: {{ $.Values.global.secretStore.kind }}
  target:
    name: quay-users
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $.Values.global.secretStore.backend }}/global/quay-users

