{{- if .Values.rhtpa.zeroTrust.keycloak.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-cli
  namespace: {{ .Values.rhtpa.namespace }}
  labels:
    {{- include "rhtpa-operator.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Create before RHTPA CR
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: oidc-cli
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: secret/data/global/rhtpa-oidc-cli-secret
      property: client-secret
{{- end }}

