{{- if .Values.rhtas.zeroTrust.spire.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rhtas.namespace }}-artifact-signer
  namespace: {{ .Values.rhtas.namespace }}
  labels:
    {{- include "rhtas-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: signer
data:
  artifact-signer.py: |
{{- .Files.Get "files/artifact-signer.py" | nindent 4 }}
{{- end }}

