apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vaultSpokeJwtConfig.serviceAccount.name }}
  namespace: vault
  labels:
    {{- include "vault-spoke-jwt-config.labels" . | nindent 4 }}

