{{- if .Values.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ztvp-certificates.fullname" . }}-ca-extractor-initial
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
  labels:
    {{- include "ztvp-certificates.labels" . | nindent 4 }}
    app.kubernetes.io/component: initial-extraction
spec:
  {{- if not .Values.debug.keepFailedJobs }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  {{- end }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "ztvp-certificates.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: initial-extraction
    spec:
      serviceAccountName: {{ include "ztvp-certificates.serviceAccountName" . }}
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: ca-extractor
        image: {{ .Values.job.image.registry }}/{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
        resources:
          {{- toYaml .Values.job.resources | nindent 10 }}
        command:
          - /bin/bash
          - -c
          - |
            {{- tpl (.Files.Get "files/extract-certificates.sh") . | nindent 12 }}
{{- end }}

